kp image create k8s-todo-backend \
--tag harbor.withtanzu.com/pa-dburkhalter/k8s-todo-backend \
--local-path /Users/dburkhalter/iena/pivotal/github/k8s-todo-app/backend/target/k8s-todo-backend.jar  \
--env BP_JVM_VERSION=11 \
--env BP_OCI_DESCRIPTION="k8s-todo-app Application" \
--env 'BP_IMAGE_LABELS=relise="k8s-todo-app v0.12.0 - 10.aout.2021"' \
--env BP_OCI_AUTHORS="Tanzu South EMEA" \
--env BP_OCI_TITLE="Spring Boot k8s-todo-app" \
--env JBP_LOG_LEVEL=debug \
--env BP_OCI_DOCUMENTATION="created on 10.aout.2021" \
--output yaml --dry-run-with-image-upload  > k8s-todo-backend_image.yaml