spring:
  application:
    name: k8s-todo-backend
  jpa:
    generate-ddl: true
    hibernate:
      ddl-auto: update
management:
  endpoints:
    web:
      exposure:
#        include: health, prometheus
        include: "*"
# dib - 9.aout
# 
logging:
  level:
#
# Enable logging to verify that HikariCP is used, the second entry is specific to HikariCP
    org.hibernate.SQL: info
    org.hibernate: warn
    org.hibernate.type.descriptor.sql.BasicBinder: warn
 # 12.aout
    com.zaxxer.hikari.HikariConfig: info
    # trace > info
    com.zaxxer.hikari: info
